name: Build and test Angular
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macos-latest
          #- windows-latest
        node_version:
          #- 12
          #- 14
          - 16

    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm

      - name: npm install, run test and build production
        run: |
          npm install
          npm run test:prod